version: '3.8'

services:
  mobiauto-db:
    image: postgres:latest
    container_name: mobiauto-db
    networks:
      - mobiauto
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  mobiauto:
    driver: bridge