spring:
  application:
    name: mobiauto
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mobiauto-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration

